dist: trusty
language: cpp

python:
  - "2.7"

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test 
    packages:
      - doxygen
      - g++-6

before_install:
  - pip install --upgrade pip
  - pip install --user cpp-coveralls
      
script:
  - doxygen Doxyfile
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./strutil-tests
  
after_success:
  - coveralls --root . -E ".*googletest.*" -E ".*CMakeFiles.*"

deploy:
  provider: pages
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
